//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealnetPortal.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DealnetPortal.Api.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Conditioner.
        /// </summary>
        public static string AirConditioner {
            get {
                return ResourceManager.GetString("AirConditioner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Handler.
        /// </summary>
        public static string AirHandler {
            get {
                return ResourceManager.GetString("AirHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and then you will be prompted to change the password..
        /// </summary>
        public static string AndThenYouPromptedToChangePass {
            get {
                return ResourceManager.GetString("AndThenYouPromptedToChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application submitted.
        /// </summary>
        public static string ApplicationSubmitted {
            get {
                return ResourceManager.GetString("ApplicationSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basement Repair.
        /// </summary>
        public static string BasementRepair {
            get {
                return ResourceManager.GetString("BasementRepair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bathroom.
        /// </summary>
        public static string Bathroom {
            get {
                return ResourceManager.GetString("Bathroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boiler.
        /// </summary>
        public static string Boiler {
            get {
                return ResourceManager.GetString("Boiler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business phone.
        /// </summary>
        public static string BusinessPhone {
            get {
                return ResourceManager.GetString("BusinessPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell phone.
        /// </summary>
        public static string CellPhone {
            get {
                return ResourceManager.GetString("CellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client data inputted.
        /// </summary>
        public static string ClientDataInputted {
            get {
                return ResourceManager.GetString("ClientDataInputted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment from customer.
        /// </summary>
        public static string CommentFromCustomer {
            get {
                return ResourceManager.GetString("CommentFromCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations.
        /// </summary>
        public static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        public static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract ID.
        /// </summary>
        public static string ContractId {
            get {
                return ResourceManager.GetString("ContractId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract {0} was declined.
        /// </summary>
        public static string ContractWasDeclined {
            get {
                return ResourceManager.GetString("ContractWasDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract {0} was successfully changed.
        /// </summary>
        public static string ContractWasSuccessfullyChanged {
            get {
                return ResourceManager.GetString("ContractWasSuccessfullyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract {0} was successfully submitted.
        /// </summary>
        public static string ContractWasSuccessfullySubmitted {
            get {
                return ResourceManager.GetString("ContractWasSuccessfullySubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit check approved.
        /// </summary>
        public static string CreditCheckApproved {
            get {
                return ResourceManager.GetString("CreditCheckApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit check declined.
        /// </summary>
        public static string CreditCheckDeclined {
            get {
                return ResourceManager.GetString("CreditCheckDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit check initiated.
        /// </summary>
        public static string CreditCheckInitiated {
            get {
                return ResourceManager.GetString("CreditCheckInitiated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer.
        /// </summary>
        public static string Dealer {
            get {
                return ResourceManager.GetString("Dealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal Info.
        /// </summary>
        public static string DealInfo {
            get {
                return ResourceManager.GetString("DealInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doors.
        /// </summary>
        public static string Doors {
            get {
                return ResourceManager.GetString("Doors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external login is already associated with an account..
        /// </summary>
        public static string EexternalLoginAlreadyAssociated {
            get {
                return ResourceManager.GetString("EexternalLoginAlreadyAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        public static string Equipment {
            get {
                return ResourceManager.GetString("Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on Register user.
        /// </summary>
        public static string ErrorOnRegisterUser {
            get {
                return ResourceManager.GetString("ErrorOnRegisterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Warranty Form.
        /// </summary>
        public static string ExtendedWarrantyForm {
            get {
                return ResourceManager.GetString("ExtendedWarrantyForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External login failure..
        /// </summary>
        public static string ExternalLoginFailure {
            get {
                return ResourceManager.GetString("ExternalLoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External service is unavailable.
        /// </summary>
        public static string ExternalServiceUnavailable {
            get {
                return ResourceManager.GetString("ExternalServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fireplace.
        /// </summary>
        public static string Fireplace {
            get {
                return ResourceManager.GetString("Fireplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flooring.
        /// </summary>
        public static string Flooring {
            get {
                return ResourceManager.GetString("Flooring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for.
        /// </summary>
        public static string For {
            get {
                return ResourceManager.GetString("For", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Furnace.
        /// </summary>
        public static string Furnace {
            get {
                return ResourceManager.GetString("Furnace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST.
        /// </summary>
        public static string Gst {
            get {
                return ResourceManager.GetString("Gst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST + PST.
        /// </summary>
        public static string GstPst {
            get {
                return ResourceManager.GetString("GstPst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GST + QST.
        /// </summary>
        public static string GstQst {
            get {
                return ResourceManager.GetString("GstQst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat Pump.
        /// </summary>
        public static string HeatPump {
            get {
                return ResourceManager.GetString("HeatPump", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hepa System.
        /// </summary>
        public static string HepaSystem {
            get {
                return ResourceManager.GetString("HepaSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Owner&apos;s Name:.
        /// </summary>
        public static string HomeOwnersName {
            get {
                return ResourceManager.GetString("HomeOwnersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home phone.
        /// </summary>
        public static string HomePhone {
            get {
                return ResourceManager.GetString("HomePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HRV.
        /// </summary>
        public static string Hrv {
            get {
                return ResourceManager.GetString("Hrv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HST.
        /// </summary>
        public static string Hst {
            get {
                return ResourceManager.GetString("Hst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HWT.
        /// </summary>
        public static string Hwt {
            get {
                return ResourceManager.GetString("Hwt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Not yet generated.
        /// </summary>
        public static string IDNotYetGenerated {
            get {
                return ResourceManager.GetString("IDNotYetGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any question please contact.
        /// </summary>
        public static string IfYouHaveQuestionsPleaseContact {
            get {
                return ResourceManager.GetString("IfYouHaveQuestionsPleaseContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any question to home professional please contact.
        /// </summary>
        public static string IfYouHaveQuestionsToHomeProfessionalPleaseContact {
            get {
                return ResourceManager.GetString("IfYouHaveQuestionsToHomeProfessionalPleaseContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case of questions please contact.
        /// </summary>
        public static string InCaseOfQuestionsPleaseContact {
            get {
                return ResourceManager.GetString("InCaseOfQuestionsPleaseContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case remarks about selected home professionals please contact.
        /// </summary>
        public static string InCaseRemarksAboutSelectedHomeProfessionalsPleaseContact {
            get {
                return ResourceManager.GetString("InCaseRemarksAboutSelectedHomeProfessionalsPleaseContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation address.
        /// </summary>
        public static string InstallationAddress {
            get {
                return ResourceManager.GetString("InstallationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user email..
        /// </summary>
        public static string InvalidUserEmail {
            get {
                return ResourceManager.GetString("InvalidUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kitchen.
        /// </summary>
        public static string Kitchen {
            get {
                return ResourceManager.GetString("Kitchen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan.
        /// </summary>
        public static string LoanApplication {
            get {
                return ResourceManager.GetString("LoanApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New customer applied for financing.
        /// </summary>
        public static string NewCustomerAppliedForFinancing {
            get {
                return ResourceManager.GetString("NewCustomerAppliedForFinancing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on the.
        /// </summary>
        public static string OnThe {
            get {
                return ResourceManager.GetString("OnThe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your on-time password is correct, now please change the password.
        /// </summary>
        public static string OntimePassCorrectNowChange {
            get {
                return ResourceManager.GetString("OntimePassCorrectNowChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Sign Agreement.
        /// </summary>
        public static string PleaseSignAgreement {
            get {
                return ResourceManager.GetString("PleaseSignAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please sign in using your email address and following password.
        /// </summary>
        public static string PleaseSignInUsingYourEmailAddressAndFollowingPassword {
            get {
                return ResourceManager.GetString("PleaseSignInUsingYourEmailAddressAndFollowingPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use it to login the portal.
        /// </summary>
        public static string PleaseUseToLoginPortal {
            get {
                return ResourceManager.GetString("PleaseUseToLoginPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plumbing.
        /// </summary>
        public static string Plumbing {
            get {
                return ResourceManager.GetString("Plumbing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Porch Enclosure.
        /// </summary>
        public static string PorchEnclosure {
            get {
                return ResourceManager.GetString("PorchEnclosure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-approved.
        /// </summary>
        public static string PreApproved {
            get {
                return ResourceManager.GetString("PreApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental.
        /// </summary>
        public static string RentalApplication {
            get {
                return ResourceManager.GetString("RentalApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rental (HWT).
        /// </summary>
        public static string RentalApplicationHwt {
            get {
                return ResourceManager.GetString("RentalApplicationHwt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roofing.
        /// </summary>
        public static string Roofing {
            get {
                return ResourceManager.GetString("Roofing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SalesRep.
        /// </summary>
        public static string SalesRep {
            get {
                return ResourceManager.GetString("SalesRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security System.
        /// </summary>
        public static string SecuritySystem {
            get {
                return ResourceManager.GetString("SecuritySystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected type of service.
        /// </summary>
        public static string SelectedTypeOfService {
            get {
                return ResourceManager.GetString("SelectedTypeOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent to audit.
        /// </summary>
        public static string SentToAudit {
            get {
                return ResourceManager.GetString("SentToAudit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siding.
        /// </summary>
        public static string Siding {
            get {
                return ResourceManager.GetString("Siding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed Contract.
        /// </summary>
        public static string SignedContract {
            get {
                return ResourceManager.GetString("SignedContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed Installation Certificate.
        /// </summary>
        public static string SignedInstallationCertificate {
            get {
                return ResourceManager.GetString("SignedInstallationCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started to fill new contract.
        /// </summary>
        public static string StartedToFillNewContract {
            get {
                return ResourceManager.GetString("StartedToFillNewContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunrooms.
        /// </summary>
        public static string Sunrooms {
            get {
                return ResourceManager.GetString("Sunrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tankless Water Heater.
        /// </summary>
        public static string TanklessWaterHeater {
            get {
                return ResourceManager.GetString("TanklessWaterHeater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for your interest in home improvement service.
        /// </summary>
        public static string ThanksForYourInterestInHomeImprovementService {
            get {
                return ResourceManager.GetString("ThanksForYourInterestInHomeImprovementService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for applying for financing..
        /// </summary>
        public static string ThankYouForApplyingForFinancing {
            get {
                return ResourceManager.GetString("ThankYouForApplyingForFinancing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Party Verification Call.
        /// </summary>
        public static string ThirdPartyVerificationCall {
            get {
                return ResourceManager.GetString("ThirdPartyVerificationCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your one-time password:.
        /// </summary>
        public static string ThisIsYourOnetimePass {
            get {
                return ResourceManager.GetString("ThisIsYourOnetimePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your password:.
        /// </summary>
        public static string ThisIsYourPass {
            get {
                return ResourceManager.GetString("ThisIsYourPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Application:.
        /// </summary>
        public static string TypeOfApplication {
            get {
                return ResourceManager.GetString("TypeOfApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown application to log in..
        /// </summary>
        public static string UnknownApplicationToLogIn {
            get {
                return ResourceManager.GetString("UnknownApplicationToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown application to register.
        /// </summary>
        public static string UnknownApplicationToRegister {
            get {
                return ResourceManager.GetString("UnknownApplicationToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password is incorrect..
        /// </summary>
        public static string UserNamerPasswordIncorrect {
            get {
                return ResourceManager.GetString("UserNamerPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy of Void Personal Cheque.
        /// </summary>
        public static string VoidPersonalChequeCopy {
            get {
                return ResourceManager.GetString("VoidPersonalChequeCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Treatment System.
        /// </summary>
        public static string WaterTreatmentSystem {
            get {
                return ResourceManager.GetString("WaterTreatmentSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’re looking for the best professional for your home improvement project.
        /// </summary>
        public static string WeAreLookingForTheBestProfessionalForYourHomeImprovementProject {
            get {
                return ResourceManager.GetString("WeAreLookingForTheBestProfessionalForYourHomeImprovementProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We’re now looking for the best home professional in your area - selected contractor will contact you soon..
        /// </summary>
        public static string WeAreNowLookingForheBest {
            get {
                return ResourceManager.GetString("WeAreNowLookingForheBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We found home professional for your home improvement project.
        /// </summary>
        public static string WeFoundHomeProfessionalForYour {
            get {
                return ResourceManager.GetString("WeFoundHomeProfessionalForYour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} will contact you soon..
        /// </summary>
        public static string WillContactYouSoon {
            get {
                return ResourceManager.GetString("WillContactYouSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to will contact you soon.
        /// </summary>
        public static string WillContactYouSoonText {
            get {
                return ResourceManager.GetString("WillContactYouSoonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string Windows {
            get {
                return ResourceManager.GetString("Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can view this deal here.
        /// </summary>
        public static string YouCanViewThisDealHere {
            get {
                return ResourceManager.GetString("YouCanViewThisDealHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can view your account on.
        /// </summary>
        public static string YouCanViewYourAccountOn {
            get {
                return ResourceManager.GetString("YouCanViewYourAccountOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been.
        /// </summary>
        public static string YouHaveBeen {
            get {
                return ResourceManager.GetString("YouHaveBeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been pre-approved for ${0}..
        /// </summary>
        public static string YouHaveBeenPreapprovedFor {
            get {
                return ResourceManager.GetString("YouHaveBeenPreapprovedFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your financing application was successfully submitted..
        /// </summary>
        public static string YourFinancingApplicationWasSubmitted {
            get {
                return ResourceManager.GetString("YourFinancingApplicationWasSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your one-time password.
        /// </summary>
        public static string YourOneTimePassword {
            get {
                return ResourceManager.GetString("YourOneTimePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password.
        /// </summary>
        public static string YourPassword {
            get {
                return ResourceManager.GetString("YourPassword", resourceCulture);
            }
        }
    }
}
