//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealnetPortal.Api.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DealnetPortal.Api.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and then you will be prompted to change the password..
        /// </summary>
        public static string AndThenYouPromptedToChangePass {
            get {
                return ResourceManager.GetString("AndThenYouPromptedToChangePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract {0} was declined.
        /// </summary>
        public static string ContractWasDeclined {
            get {
                return ResourceManager.GetString("ContractWasDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract {0} was successfully changed.
        /// </summary>
        public static string ContractWasSuccessfullyChanged {
            get {
                return ResourceManager.GetString("ContractWasSuccessfullyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract {0} was successfully submitted.
        /// </summary>
        public static string ContractWasSuccessfullySubmitted {
            get {
                return ResourceManager.GetString("ContractWasSuccessfullySubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external login is already associated with an account..
        /// </summary>
        public static string EexternalLoginAlreadyAssociated {
            get {
                return ResourceManager.GetString("EexternalLoginAlreadyAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on Register user.
        /// </summary>
        public static string ErrorOnRegisterUser {
            get {
                return ResourceManager.GetString("ErrorOnRegisterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External login failure..
        /// </summary>
        public static string ExternalLoginFailure {
            get {
                return ResourceManager.GetString("ExternalLoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External service is unavailable.
        /// </summary>
        public static string ExternalServiceUnavailable {
            get {
                return ResourceManager.GetString("ExternalServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Owner&apos;s Name:.
        /// </summary>
        public static string HomeOwnersName {
            get {
                return ResourceManager.GetString("HomeOwnersName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user email..
        /// </summary>
        public static string InvalidUserEmail {
            get {
                return ResourceManager.GetString("InvalidUserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your on-time password is correct, now please change the password.
        /// </summary>
        public static string OntimePassCorrectNowChange {
            get {
                return ResourceManager.GetString("OntimePassCorrectNowChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Sign Agreement.
        /// </summary>
        public static string PleaseSignAgreement {
            get {
                return ResourceManager.GetString("PleaseSignAgreement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use it to login the portal.
        /// </summary>
        public static string PleaseUseToLoginPortal {
            get {
                return ResourceManager.GetString("PleaseUseToLoginPortal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your one-time password:.
        /// </summary>
        public static string ThisIsYourOnetimePass {
            get {
                return ResourceManager.GetString("ThisIsYourOnetimePass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is your password:.
        /// </summary>
        public static string ThisIsYourPass {
            get {
                return ResourceManager.GetString("ThisIsYourPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Application:.
        /// </summary>
        public static string TypeOfApplication {
            get {
                return ResourceManager.GetString("TypeOfApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown application to log in..
        /// </summary>
        public static string UnknownApplicationToLogIn {
            get {
                return ResourceManager.GetString("UnknownApplicationToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown application to register.
        /// </summary>
        public static string UnknownApplicationToRegister {
            get {
                return ResourceManager.GetString("UnknownApplicationToRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name or password is incorrect..
        /// </summary>
        public static string UserNamerPasswordIncorrect {
            get {
                return ResourceManager.GetString("UserNamerPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your one-time password.
        /// </summary>
        public static string YourOneTimePassword {
            get {
                return ResourceManager.GetString("YourOneTimePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password.
        /// </summary>
        public static string YourPassword {
            get {
                return ResourceManager.GetString("YourPassword", resourceCulture);
            }
        }
    }
}
