version: 0.2

env:
  variables:
    SOLUTION: .\Server\DealnetPortal.Server.sln
    PACKAGE_DIRECTORY: .\Server\packages
    DOTNET_FRAMEWORK: 4.6.1

phases:
  build:
    commands:
      - dotnet publish -c AWSProduction -o ./deployment Server/DealnetPortal.Api.csproj      
artifacts:
  files:
    - .\Server\deployment\*
