version: 0.2

env:
  variables:
    SOLUTION: .\Server\DealnetPortal.Server.sln
    PACKAGE_DIRECTORY: .\Server\packages
    DOTNET_FRAMEWORK: 4.6.1

phases:
  build:
    commands:
      - '& "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" restore $env:SOLUTION -PackagesDirectory $env:PACKAGE_DIRECTORY'
      - '& "C:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" -p:FrameworkPathOverride="C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v$env:DOTNET_FRAMEWORK" $env:SOLUTION'
artifacts:
  files:
    - .\Server\deployment\*
