//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DealnetPortal.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DealnetPortal.Web.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Req..
        /// </summary>
        public static string ActionReq {
            get {
                return ResourceManager.GetString("ActionReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add comment.
        /// </summary>
        public static string AddComment {
            get {
                return ResourceManager.GetString("AddComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Applicant.
        /// </summary>
        public static string AdditionalApplicant {
            get {
                return ResourceManager.GetString("AdditionalApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Contract Information.
        /// </summary>
        public static string AdditionalContractInformation {
            get {
                return ResourceManager.GetString("AdditionalContractInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Information.
        /// </summary>
        public static string AddressInformation {
            get {
                return ResourceManager.GetString("AddressInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymous.
        /// </summary>
        public static string Anonymous {
            get {
                return ResourceManager.GetString("Anonymous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to answer(s).
        /// </summary>
        public static string Answers {
            get {
                return ResourceManager.GetString("Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to top.
        /// </summary>
        public static string BackToTop {
            get {
                return ResourceManager.GetString("BackToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change your password.
        /// </summary>
        public static string ChangeYourPassword {
            get {
                return ResourceManager.GetString("ChangeYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Filters.
        /// </summary>
        public static string ClearFilters {
            get {
                return ResourceManager.GetString("ClearFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract.
        /// </summary>
        public static string Contract {
            get {
                return ResourceManager.GetString("Contract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date From.
        /// </summary>
        public static string DateFrom {
            get {
                return ResourceManager.GetString("DateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date To.
        /// </summary>
        public static string DateTo {
            get {
                return ResourceManager.GetString("DateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealer Name.
        /// </summary>
        public static string DealerName {
            get {
                return ResourceManager.GetString("DealerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal Flow Overview.
        /// </summary>
        public static string DealFlowOverview {
            get {
                return ResourceManager.GetString("DealFlowOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal Info.
        /// </summary>
        public static string DealInfo {
            get {
                return ResourceManager.GetString("DealInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal Information.
        /// </summary>
        public static string DealInformation {
            get {
                return ResourceManager.GetString("DealInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal Status.
        /// </summary>
        public static string DealStatus {
            get {
                return ResourceManager.GetString("DealStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deal Type.
        /// </summary>
        public static string DealType {
            get {
                return ResourceManager.GetString("DealType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detailed Info.
        /// </summary>
        public static string DetailedInfo {
            get {
                return ResourceManager.GetString("DetailedInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of a document can&apos;t be empty.
        /// </summary>
        public static string DocumentNameEmpty {
            get {
                return ResourceManager.GetString("DocumentNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EcoHome Financial is a Canadian owned finance company providing custom consumer financing and loan products to the HVAC and home improvement markets. We manage all of our business in-house..
        /// </summary>
        public static string EcoHomeAbout1 {
            get {
                return ResourceManager.GetString("EcoHomeAbout1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We partner with leading dealers and manufacturers to deliver what is needed to succeed in today’s competitive arena – hassle free finance programs for dealers and their customers..
        /// </summary>
        public static string EcoHomeAbout2 {
            get {
                return ResourceManager.GetString("EcoHomeAbout2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Give your customers the ability to purchase now, and the ability to purchase more. We deliver what you need to succeed..
        /// </summary>
        public static string EcoHomeAbout3 {
            get {
                return ResourceManager.GetString("EcoHomeAbout3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing.
        /// </summary>
        public static string Editing {
            get {
                return ResourceManager.GetString("Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entries.
        /// </summary>
        public static string Entries {
            get {
                return ResourceManager.GetString("Entries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment.
        /// </summary>
        public static string Equipment {
            get {
                return ResourceManager.GetString("Equipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Equipment Information.
        /// </summary>
        public static string EquipmentInformation {
            get {
                return ResourceManager.GetString("EquipmentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while adding comment.
        /// </summary>
        public static string ErrorWhileAddingComment {
            get {
                return ResourceManager.GetString("ErrorWhileAddingComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while removing comment.
        /// </summary>
        public static string ErrorWhileRemovingComment {
            get {
                return ResourceManager.GetString("ErrorWhileRemovingComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while uploading file..
        /// </summary>
        public static string ErrorWhileUploadingFile {
            get {
                return ResourceManager.GetString("ErrorWhileUploadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Equipment Information.
        /// </summary>
        public static string ExistingEquipmentInformation {
            get {
                return ResourceManager.GetString("ExistingEquipmentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export All to Excel.
        /// </summary>
        public static string ExportAllToExcel {
            get {
                return ResourceManager.GetString("ExportAllToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        public static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find us.
        /// </summary>
        public static string FindUs {
            get {
                return ResourceManager.GetString("FindUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funding Checklist.
        /// </summary>
        public static string FundingChecklist {
            get {
                return ResourceManager.GetString("FundingChecklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to app.
        /// </summary>
        public static string GoToApp {
            get {
                return ResourceManager.GetString("GoToApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Step .
        /// </summary>
        public static string GoToStep {
            get {
                return ResourceManager.GetString("GoToStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grand Total:.
        /// </summary>
        public static string GrandTotal {
            get {
                return ResourceManager.GetString("GrandTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Great work!.
        /// </summary>
        public static string GreatWork {
            get {
                return ResourceManager.GetString("GreatWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Owner Information.
        /// </summary>
        public static string HomeOwnerInformation {
            get {
                return ResourceManager.GetString("HomeOwnerInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HST.
        /// </summary>
        public static string Hst {
            get {
                return ResourceManager.GetString("Hst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you change Home Owner Information you will have to pass Credit Check step again.
        /// </summary>
        public static string IfYouChangeInfo {
            get {
                return ResourceManager.GetString("IfYouChangeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is rental?.
        /// </summary>
        public static string IsRental {
            get {
                return ResourceManager.GetString("IsRental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loan Term.
        /// </summary>
        public static string LoanTerm {
            get {
                return ResourceManager.GetString("LoanTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log In.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing Address.
        /// </summary>
        public static string MailingAddress {
            get {
                return ResourceManager.GetString("MailingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum file size is limited to 50 MB for a single file..
        /// </summary>
        public static string MaximumFileSize {
            get {
                return ResourceManager.GetString("MaximumFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONTHLY PAYMENT.
        /// </summary>
        public static string MonthlyPayment {
            get {
                return ResourceManager.GetString("MonthlyPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Deals.
        /// </summary>
        public static string MyDeals {
            get {
                return ResourceManager.GetString("MyDeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Work Items.
        /// </summary>
        public static string MyWorkItems {
            get {
                return ResourceManager.GetString("MyWorkItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to step .
        /// </summary>
        public static string NavigateToStep {
            get {
                return ResourceManager.GetString("NavigateToStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Application.
        /// </summary>
        public static string NewApplication {
            get {
                return ResourceManager.GetString("NewApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching records found.
        /// </summary>
        public static string NoMatchingRecordsFound {
            get {
                return ResourceManager.GetString("NoMatchingRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not selected.
        /// </summary>
        public static string NotSelected {
            get {
                return ResourceManager.GetString("NotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now you can log in with your new password..
        /// </summary>
        public static string NowYouCanLogIn {
            get {
                return ResourceManager.GetString("NowYouCanLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On this email you will get a new password.
        /// </summary>
        public static string OnThisEmail {
            get {
                return ResourceManager.GetString("OnThisEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Documents.
        /// </summary>
        public static string OtherDocuments {
            get {
                return ResourceManager.GetString("OtherDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password was successfully changed..
        /// </summary>
        public static string PasswordWasChanged {
            get {
                return ResourceManager.GetString("PasswordWasChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Information.
        /// </summary>
        public static string PaymentInformation {
            get {
                return ResourceManager.GetString("PaymentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please check your email for one-time password..
        /// </summary>
        public static string PleaseCheckEmail {
            get {
                return ResourceManager.GetString("PleaseCheckEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply.
        /// </summary>
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report for contract.
        /// </summary>
        public static string ReportForContract {
            get {
                return ResourceManager.GetString("ReportForContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Term.
        /// </summary>
        public static string RequestedTerm {
            get {
                return ResourceManager.GetString("RequestedTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reupload.
        /// </summary>
        public static string Reupload {
            get {
                return ResourceManager.GetString("Reupload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Rep.
        /// </summary>
        public static string SalesRep {
            get {
                return ResourceManager.GetString("SalesRep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub-Dealer.
        /// </summary>
        public static string SubDealer {
            get {
                return ResourceManager.GetString("SubDealer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total for Selected:.
        /// </summary>
        public static string TotalForSelected {
            get {
                return ResourceManager.GetString("TotalForSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL MONTHLY PAYMENT (TAX INCL.).
        /// </summary>
        public static string TotalMonthlyPaymentWithTaxes {
            get {
                return ResourceManager.GetString("TotalMonthlyPaymentWithTaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL VALUE.
        /// </summary>
        public static string TotalValue {
            get {
                return ResourceManager.GetString("TotalValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Equipment.
        /// </summary>
        public static string TypeOfEquipment {
            get {
                return ResourceManager.GetString("TypeOfEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Payment.
        /// </summary>
        public static string TypeOfPayment {
            get {
                return ResourceManager.GetString("TypeOfPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value of Deal.
        /// </summary>
        public static string ValueOfDeal {
            get {
                return ResourceManager.GetString("ValueOfDeal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a reply....
        /// </summary>
        public static string WriteReply {
            get {
                return ResourceManager.GetString("WriteReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been successfully registered,.
        /// </summary>
        public static string YouHaveBeenRegistered {
            get {
                return ResourceManager.GetString("YouHaveBeenRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to your comment.
        /// </summary>
        public static string YourComment {
            get {
                return ResourceManager.GetString("YourComment", resourceCulture);
            }
        }
    }
}
